name: Selenium POM Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install selenium
        pip install pytest
        pip install webdriver-manager

    - name: Run Selenium Tests
      run: |
        pytest TestCases/test_login.py -v